### ISSUE TITLE
Inspect / correct configurations for development tools and processes

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1251]
While working on v5, I noticed a couple of things that might use some checking:

### TODO:
- [ ] 1. Prettier - whole project scanned
- [ ] 2. `lint-staged` - incorrect file filter applied
- [ ] 3. ESLint - not ignoring `build` files

### 1. Prettier - whole project scanned
While running pre-commit actions, this prettier command takes a lot of time, because it's actually scanning the whole project, not only the files that are about to be committed.

![Snipaste_2020-09-18_12-04-24](https://user-images.githubusercontent.com/5121148/93590405-bb497280-f9ae-11ea-8cb6-c4bec22017b7.png)

### 2. `lint-staged` - incorrect file filter applied
This here says only `"**/*.js"` needs to be included. We should add `ts,tsx` here as well.

![Snipaste_2020-09-18_12-04-47](https://user-images.githubusercontent.com/5121148/93590441-cc927f00-f9ae-11ea-9afc-c11294572ef4.png)

### 3. ESLint - not ignoring `build` files
Running `yarn eslint` inspects the whole project, including build files, which should **NOT** be happening.

![Snipaste_2020-09-18_12-05-16](https://user-images.githubusercontent.com/5121148/93590396-b71d5500-f9ae-11ea-92ff-f70aa3248d43.png)
![Snipaste_2020-09-18_12-05-42](https://user-images.githubusercontent.com/5121148/93590399-b84e8200-f9ae-11ea-961f-1b5a880db7ce.png)

**Comment by iamdarshshah** [comment]
Hey @doitadrian 👋 ,

 If the issue still exists, would like to have a look into this. Let me know if someone is already working on solving this. Thanks

**Comment by doitadrian** [comment]
Sure, go ahead @iamdarshshah! 👍 

Let us know for any questions.

**Comment by doitadrian** [comment]
P.S. Note that you need to branch from `v5` branch.

We don't need this for `master`.

**Comment by iamdarshshah** [comment]
@doitadrian Sure noted. I'm on it! 👍

**Comment by iamdarshshah** [comment]
@doitadrian Check PR #1301 that will fix this issue for branch `v5` & let me know if there is anything that needs to change. Thanks
