### ISSUE TITLE
Improve Error Handling - Errors Not Shown In Browser

### ISSUE THREAD

**Issue by Ashu96** [webiny/webiny-js#1614]
## This is:
- Maintenance

## Detailed Description
This is a master issue that is consist of the following sub-tasks:
- [x]  [Add: visual feedback when an error happens (Admin Area) #1611](https://github.com/webiny/webiny-js/issues/1611)
- [x]  [Debug: why the error is not being returned from a lambda function #1612](https://github.com/webiny/webiny-js/issues/1612)
- [x]  [Research: how can we set DEBUG=true as a default for the dev environment #1613](https://github.com/webiny/webiny-js/issues/1613)
