### ISSUE TITLE
Add Cypress Tests for Webiny Applications

### ISSUE THREAD

**Issue by Ashu96** [webiny/webiny-js#1648]
## This is:
- Improvement

## Detailed Description:
We need to add End-to-End tests for all Webiny applications using Cypress.
This issue contains the list of all sub-tasks that describes the scope of this task.

### Action Items:
- [x] write test cases for the [Form Builder](https://github.com/webiny/webiny-js/issues/1642) app
- [x] write test cases for the [I18N](https://github.com/webiny/webiny-js/issues/1643) app
- [ ] write test cases for the [Headless CMS](https://github.com/webiny/webiny-js/issues/1644) app
- [x] write test cases for the [Security](https://github.com/webiny/webiny-js/issues/1645) app
- [x] write test cases for the [File Manager](https://github.com/webiny/webiny-js/issues/1646) app
- [ ] write test cases for the [Page Builder](https://github.com/webiny/webiny-js/issues/1647) app
