### ISSUE TITLE
Feature: Page Builder storage operations

### ISSUE THREAD

**Issue by brunozoric** [webiny/webiny-js#1868]
## Detailed Description
We need to be able to implement different storages (databases) for the page builder data.

## Solutions
Refactor existing api-page-builder to support different storage operations and extract current logic into separate package.

## Tasks
- [x] Create storage operations plugins and interfaces to be implemented and extended in the ddb and ddb+es packages
- [x] Extract existing storage operations logic into the api-page-bilder-so-ddb-es package
- [ ] _Create new storage operations package for ddb only (api-page-builder-so-ddb)_ - will be in separate PR
- [ ] Refactor tests to be able to run multiple storage operations
- [ ] Add lifecycle hooks to all crud operations (before and after)
