### ISSUE TITLE
I18N Support

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#745]
Work in progress

## This is:

- Feature request

## Detailed Description
In order to consider the Webiny's I18N solution complete, we need to finish a couple of things. 

Ideally, it would be awesome if we could manage to resolve all of these. Otherwise, I'd say the I18N interface is the most important one.

Let's take a look.

## TODO

- [x] `i18n.ns`
  - With `i18n.namespace` method for defining a namespace, we could have `i18n.ns` as an alternative. Will make the code a bit cleaner.

- [ ] Finish scanner tool
  - The tool must be able to recognize both `i18n.namespace` (already works) and `i18n.ns` calls (I believe this does not work) 
  - Currently, the CLI can only be run by executing the `bin.js` directly, there is no separate command like e.g. `i18n scan` or `webiny-i18n scan`. It would be nice to have a nice CLI.
  - Integrate the scanner tool with the `@webiny/cli`. For this to work, the scanner tool must be usable programmatically, via JS. This is already true I believe.

- [ ] Change the structure of texts
  - Simplify the text file that the scanner tool generates. We don't need IDs in it, just use namespace as the root key, and inside of it, nest scanned texts as keys, and empty strings as values. For example:
```js
// Namespace definition: const t = i18n.ns("app-security/admin/roles-form");
// Usage in code (e.g. in a React component): {t'Save form'}

// The scanner should produce the following output:
{
  "app-security": {
    "admin": {
      "roles-form": {
        "Save Form": ""
      }
    }
  }
}
```

- [ ] Redo the React library (`@webiny/i18n-react`)
Currently, when using `t` in React, it only returns a string and occasionally a React component (if there are any components included in the variables). But, after some thinking, I figured that, in the React world, the `t` must always return a React component. There are a couple of benefits that this approach gives us:

   - The top React provider can trigger refreshing of all texts on the screen when the user changes the language.
  - This also allows us to render a fallback component if the translations are being loaded, e.g. a small loading indicator instead of the text.
  - What about cases in which we want to pass s simple string instead of a component? Well, we still want to be able to do that. This is especially important if you want to pass a placeholder for simple input, which must be a  simple string. It seems that we'll need to add a way to tell the `t` to return a string for these cases. The smart way to do this would be to tell the `t` which "processor" to use (we already have a concept of processors in the code). In a React world, by default, the "React processor" is being used, but in a Node.js world, just the "default" one (just returns plain strings).
  -  Continuing with the previous point, another problem that arises here is the inability to refresh the text if a user changed the language. Because of this, we'll also need to create a simple React hook, e.g. `useI18N`. This component will make sure that the component in which it's used, is re-rendered on language changes.
  - Do remember to optimize for unnecessary re-renders. E.g. if we pass a `t("Text")` to another component, we must make sure that it doesn't get re-rendered because it's receiving different values from the `t("Text")`. So in other words, the value that comes out of the `t("Text")` must be memoized properly. [React.memo](https://reactjs.org/blog/2018/10/23/react-v-16-6.html#reactmemo) could be of use here.

- [ ] I18N Translations interface
We want to have an easy-to-use interface via which the users will be able to control translations. The funny thing is, we already had the interface in a very old version of Webiny and it worked great. Here's a couple of screenshots that show what needs to be recreated:
  - Main screen - shows what percentage of current text is translated: ![image](https://user-images.githubusercontent.com/5121148/76083574-41234480-5fae-11ea-8985-1d6185810cc9.png)
  - Continuing from the previous image, a single text can have many translations: ![image](https://user-images.githubusercontent.com/5121148/76083603-4e403380-5fae-11ea-80da-66ec744e409f.png)
  - In the locale ![image](https://user-images.githubusercontent.com/5121148/76083582-45e7f880-5fae-11ea-9b68-8b6e673b5493.png)
  - ![image](https://user-images.githubusercontent.com/5121148/76083596-4a141600-5fae-11ea-8a50-8e7bb9a5f2f3.png)

With this interface, users will not only be able to edit the translations inline, but also import/export translations via translation files. This, for example, enables the website owner to pass the file to a professional translator, and let him do the translations for the whole site.

Note that we already have the `I18NLocale` model defined, but it's missing some fields like date/time/number formatting, and maybe something else too. Screenshots should give you a clue what might be missing.

- [ ] In the I18N class, we have special methods like `price`, `number`, `date` and similar. We must make sure users can choose which libraries they want to use internally in these methods (specify via plugins?). 

  - Why aren't we coding this ourselves? Because libraries often have a lot of things ready for us. For example, in using moment.js, we already have translations for months for a lot of languages.

- [ ] The fun one ☺️ - we have a lot of apps that don't use the `t` function, unfortunately. We'll have to go through these apps and utilize it where needed. When we accomplish this, we'll also need to close #617, #618, #619.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
