### ISSUE TITLE
create-webiny-project

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#764]
Create a `create-webiny-project` tool to bootstrap Webiny projects using `npx create-webiny-project`.

## Why?
Currently, project creation is handled by our `@webiny/cli` package which is installed globally. We want to move away from global installations and handle everything from withing the project (same way `create-react-app` does). The CLI will only contain tools to build/deploy/scaffold the existing project and will be installed as a project dependency (not globally).

This will also give us a chance to create different project templates, e.g.: `cwp-template-basic`, `cwp-template-page-builder`, `cwp-template-headless`, `cwp-template-full`, etc.

## The Goal
The goal of this tool is to setup a Webiny project which is ready for deployment and development of new apps and APIs. The setup must take care of all TS configs, babel configs, workspaces, so a developer can start developing new things right away.

## Implementation tasks
- [ ] create a new package `create-webiny-project` in the `webiny-js` repo (see how [create-react-app](https://github.com/facebook/create-react-app/tree/master/packages/create-react-app) works for inspiration). 
- [ ] figure out how to dynamically download the requested template (`--template=basic` should download and setup `cwp-template-basic`). Templates must NOT be dependencies of the `create-webiny-project` tool itself; they must be downloaded dynamically.
- [ ] create a `cwp-template-basic` package which contains a project template (see [cra-template-typescript](https://github.com/facebook/create-react-app/tree/master/packages/cra-template-typescript) for inspiration), @Pavel910 will provide the template content itself once the basic mechanics are in place.

For example:
```
npx create-webiny-project my-webiny --template=basic
```
results in the following `webiny.config.js` file being created in the root of the new project:

```js
module.exports = {
    projectName: "my-webiny"
};
```

## Notes regarding templates
The idea is that templates are modules that contain `template` folder with static files, and also an `index.js` (or anything that is defined by `main` field in package.json) that can be executed to setup the template. 

Ideally, CWP (create-webiny-project), will copy the `{templatePackage}/template` and then require the package and execute the default export. This is necessary to post-process the template files and generate random secret values, etc.

## Task notes
The base branch for this task is https://github.com/webiny/webiny-js/tree/feat/headless-latest.

- use `yarn` exclusively (`npm` doesn't support monorepos at this point so we only work with `yarn`)
- use `yargs` for CLI command parsing (CRA uses `commander`, but we use `yargs` everywhere)
- don't copy CRA exactly - just see how it works to get the general idea. We need something really simple, and we'll improve as we go.
- do your best to make the tool work on different platforms (we have OSX and Windows users in the team so ask them to test it if you're unable to do so yourself)
- use https://github.com/verdaccio/verdaccio to publish and test the tool locally - this is a priceless tool to test real-life usage on your local machine
