### ISSUE TITLE
Page Builder - enable support for I18N

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#765]
## This is:

- Feature request

## Detailed Description
Often users need to create their pages in different languages, and currently, this is not possible.

This issue explains what needs to be done in order to introduce I18N support for the Page Builder app.

## Tasks
The tasks are broken up into the following sections:
- Page Builder - editor
- Pages view
- Categories view
- Menus view
- Installation

### Page Builder - editor
- [ ] Create language selector in the Page Builder editor

Since pages can now be multi-language, we need to add a language selector in the actual editor. This would be a good place to put it:

![image](https://user-images.githubusercontent.com/5121148/77151106-9757b380-6a95-11ea-975a-06ee82948611.png)

To get the list of all available locales in the system, you can use the `useI18N` hook:
```js
import { useI18N } from "@webiny/app-i18n/hooks/useI18N";
```

And in your React component, you can call it like this:
```js
const { getLocale, getLocales } = useI18N();
```

This menu should be registered as a plugin, here: `packages/app-page-builder/src/editor/plugins/defaultBar/index.tsx:31`.

Note, you don't need to show the selector if user only has one locale set up (this is done via [the I18N app](https://d2a1nm2n4r6rly.cloudfront.net/admin/i18n/locales)).

- [ ] Enable the language selector

Creating a language selector will enable users to edit the same page in different languages, without leaving the editor. But what exactly happens when the user selects a different language? 

Well, we decided that on the backend, we will just load another page entry from the database. In other words, the user sees it as he's working on the same page, but, in the database, it's another entry. A short presentation of the concept:
```
id  title       locale          revision
1   About us    localeA_ID      1
2   Über uns    localeB_ID      1
```
Make sure to check the data in the `PbPage` collection and the actual `PbPage` Commodo model, located in `packages/api-page-builder/src/plugins/models/pbPage.model.ts`). 

Note that this also means that these language variations of the same page will probably need to be linked together in some way in the database, so that when you click on a different language in the language selector, the backend knows which page to return. Try to come up with an idea yourself.

We've seen what happens if a page for the selected language exists, but what if it doesn't?
If the page for selected language doesn't exist already, create a copy of the currently selected one. Note that you will need to copy/paste the data from the current page. We are doing the same when a user is creating a new revision of an existing page, take a look at this: `packages/api-page-builder/src/plugins/graphql/pageResolvers/createRevisionFrom.ts:18`.

Finally, to make this all work, you will need to do the following things:
- add the `locale` field on the PbPage model (`packages/api-page-builder/src/plugins/models.ts`)
- add a field in the GraphQL schema (type `PbPage`) - `packages/api-page-builder/src/plugins/graphql/Page.ts:38`.
- you'll also need to fetch the `locale` in the actual Page Builder app, it all starts here `packages/app-page-builder/src/admin/views/Pages/Editor.tsx:99`

- [ ] Enable multi-language page URLs

Via the page settings in the Page Builder editor, users can edit the URL of the page they're working on.

![image](https://user-images.githubusercontent.com/5121148/77152457-50b78880-6a98-11ea-9013-0a4a7d82760a.png)

![image](https://user-images.githubusercontent.com/5121148/77152474-590fc380-6a98-11ea-94e6-05f236bee696.png)

Depending on if the user has created one or more locales, these URLs will look different.

A) User has one locale installed
Everything visually stays the same. 

But if we have more than one locale created in the system, the following should occur...

B) User has more than one locale installed
Since we're creating separate page entry in the database for each language, users will be able to set a different URL for each language. Basically, users will be able to do the following:

```
mysite.com/en-gb/mice
mysite.com/en-us/mice
mysite.com/it-it/topi
mysite.com/fr-fr/souris
```

Note that in the page settings, users only type the final path (e.g. "/mice" or "/topi"). But we need to let them know what the final URL will be. So, use the URL input's `description` prop to print it out for the user.

![image](https://user-images.githubusercontent.com/5121148/77153893-f4099d00-6a9a-11ea-924d-a4c23df9e7ee.png)

The language of the page should be received from the data received from the API, so pull that info from there.

- [ ] Revisions / publishing pages
Currently, a page can have [multiple revisions](https://docs.webiny.com/docs/webiny-apps/page-builder/revisions-and-publishing). Now that we have languages in the mix, we need to ensure a couple of things:

- when a brand new page is created, "I guess" we can only create a draft for the default language. Use `getLocale` form the `useI18N` hook to determine it. Or even better, let the backend determine it if possible.
- when a new revision is published, new drafts must be created for every language
- when a page is published, all of the pages for every language must be published

### Pages view
- [ ] Add language selector in the page details section

We already have a revision selector in this view. You also need to add a language selector, so that the user can check out other languages too.

![image](https://user-images.githubusercontent.com/5121148/77162777-fd036a00-6aac-11ea-9838-f4758ba74b3d.png)

Note that if the user selects a different revision (in the screenshot, we're seeing v2), when switching languages, pages from that revision need to be shown.

##### Which language should be used by default?
Use the `getLocale` from `useI18N` to get the default locale, and load the page for that locale.

- [ ] Add a language filter for the pages list

Let's try to add a drop-down menu here, which will contain a list of all locales, and once user makes a selection with it, the list will be showing pages for the selected locale only.
![image](https://user-images.githubusercontent.com/5121148/77167737-e235f300-6ab6-11ea-9a51-281032fd5e48.png)

##### Which language should be used by default?
Use the `getLocale` from `useI18N` to get the default locale, and list the pages for that locale.

### Categories module

- [ ] Add support for defining categories for different languages

Categories need to be multi-language too. But here, we won't be creating additional entries in the database for every language. Instead, we're gonna make use of the already built-in I18N capabilities.

Here we can see the categories form:
![image](https://user-images.githubusercontent.com/5121148/77163110-b06c5e80-6aad-11ea-88be-707d631d39ca.png)

The only value that should be defined for all languages is the `URL` field.

In order to do that, you need to replace the basic `Input` component with the `I18NInput` component. 

```js
import { I18NInput } from "@webiny/app-i18n/admin/components";
```

And then use it like so (example taken from the [Form Builder app](/Users/adrian/dev/wby/packages/app-form-builder/src/editor/plugins/formSettings/components/TermsOfServiceSettings.tsx) which uses this functionality in several parts):

```js
<I18NInput
  disabled={!enabled}
  label={"Terms of service message"}
  description={
    "Show this message near the submit button or event ask users to accept before submitting."
  }
/>
```

This will actually enable the user to edit the value for all locales that are created via the I18N app.

#### Changes on the backend
Note that on the backend, you will also need to change the field in the `Category` model. For the [`url`](packages/api-page-builder/src/plugins/models/pbCategory.model.ts:12) field, we use a basic string, but now you will have to use the `i18nString`, which looks like the following:

```js
import { i18nString, i18nObject } from "@webiny/api-i18n/fields";
```
Example (note that you need to pass the `context` as well):
```js
submitButtonLabel: i18nString({ context }),
```
With that, the change must also be made on the GQL schema. Replace the basic `String` field type with the `I18NString` type here: `packages/api-page-builder/src/plugins/graphql/Category.ts:18`.

Note that this type needs to be imported from the `@webiny/api-i18n` package. Check `packages/api-form-builder/src/plugins/graphql.ts:21`  to see how we've done it in the Form Builder app.

### Menus module

- [ ] Add support for defining menus for different languages

Use the same approach as for adapting the "Categories module".

![image](https://user-images.githubusercontent.com/5121148/77163200-de51a300-6aad-11ea-8d1f-fc78bd89803a.png)

This could be a bit more complicated because here you also have menu items, but just try applying the same approaches, and we'll see how it'll work. 

### Installation

When a user installs the Page Builder app, a couple of demo pages are created, just so the user gets a better feeling of the app and what it can offer.

You will have to adapt the data that's created in this process. 

I will write the necessary instructions for this part once we get there.
